[package]
authors = ["0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "High level server for hyper and tower."
edition = "2021"
homepage = "https://github.com/warlock-labls/hyper-server"
keywords = ["axum", "tonic", "hyper", "tower", "server"]
license = "MIT"
name = "hyper-server"
readme = "README.md"
repository = "https://github.com/valorem-labs-inc/hyper-server"
version = "1.0.0"

[dependencies]
http = "1.1.0"
http-body-util = "0.1.2"
hyper = "1.4.1"
hyper-util = { version = "0.1.8", features = ["server", "tokio", "server-auto", "server-graceful"] }
rustls = "0.23.13"
tokio = { version = "1.40.0", features = ["net"] }
tokio-rustls = "0.26.0"
tower = "0.5.1"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["macros"] }
