[package]
authors = ["jonathan@warlock.xyz", "0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "High level server for hyper and tower."
edition = "2021"
homepage = "https://github.com/valorem-labs-inc/hyper-server"
keywords = ["axum", "tonic", "hyper", "tower", "server"]
license = "MIT"
name = "hyper-server"
readme = "README.md"
repository = "https://github.com/warlock/hyper-server"
version = "1.0.0"


[dependencies]
## rustls
arc-swap = { version = "1", optional = true }
bytes = "1"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
http = "1.1"
http-body = "1.0.1"
http-body-util = { version = "0.1" }
hyper = { version = "1.4", features = ["http1", "http2", "server"] }
hyper-util = { version = "0.1", features = ["full"]}

## openssl
openssl = { version = "0.10" }
pin-project-lite = { version = "0.2" }
rustls = { version = "0.23" }
rustls-pemfile = { version = "2.1" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "signal"] }
tokio-openssl = { version = "0.6", optional = true }
tokio-rustls = { version = "0.26", optional = true }
tower-service = "0.3"

## proxy-protocol
ppp = { version = "2.2.0", optional = true }
tower = "0.4.13"
nix = { version = "0.29.0", features = ["signal"] }

[[example]]
name = "tower-server1"

[[example]]
name = "tower-server2"

[[example]]
name = "tower-client"
