[package]
authors = ["Programatik <programatik29@gmail.com>", "Megsdevs <megsdevs@outlook.com", "0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "High level server for hyper and tower."
edition = "2021"
homepage = "https://github.com/valorem-labs-inc/hyper-server"
keywords = ["axum", "tonic", "hyper", "tower", "server"]
license = "MIT"
name = "hyper-server"
readme = "README.md"
repository = "https://github.com/valorem-labs-inc/hyper-server"
version = "0.6.0"

[features]
default = []
tls-rustls = ["arc-swap", "pin-project-lite", "rustls", "rustls-pemfile", "tokio/fs", "tokio/time", "tokio-rustls"]
tls-openssl = ["openssl", "tokio-openssl", "pin-project-lite"]
proxy-protocol = ["ppp", "pin-project-lite"]

[dependencies]

# optional dependencies
## rustls
arc-swap = { version = "1.7.1", optional = true }
bytes = "1.7.1"
futures-util = { version = "0.3.30", default-features = false, features = ["alloc"] }
http = "0.2.12" # 1.x doesn't compile
http-body = "0.4.6" # 1.x doesn't compile
hyper = { version = "0.14.30", features = ["http1", "http2", "server", "runtime"] } # 1.x doesn't compile

## openssl
openssl = { version = "0.10.66", optional = true }
pin-project-lite = { version = "0.2.14", optional = true }
rustls = { version = "0.21.12", features = ["dangerous_configuration"], optional = true } # >=0.22 doesn't compile
rustls-pemfile = { version = "1.0.4", optional = true } # 2.x doesn't compile
tokio = { version = "1.33.0", features = ["macros", "net", "sync"] }
tokio-openssl = { version = "0.6.4", optional = true }
tokio-rustls = { version = "0.24.1", optional = true } # >=0.25 doesn't compile
tower-service = "0.3"

## proxy-protocol
ppp = { version = "2.2.0", optional = true }

[dev-dependencies]
axum = "0.7.5"
hyper = { version = "1.4.1", features = ["full"] }
tokio = { version = "1.40.0", features = ["full"] }
tower = { version = "0.5.0", features = ["util"] }
tower-http = { version = "0.5.2", features = ["add-extension"] }

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "from_std_listener_rustls"
required-features = ["tls-rustls"]
doc-scrape-examples = true

[[example]]
name = "http_and_https"
required-features = ["tls-rustls"]
doc-scrape-examples = true

[[example]]
name = "rustls_reload"
required-features = ["tls-rustls"]
doc-scrape-examples = true

[[example]]
name = "rustls_server"
required-features = ["tls-rustls"]
doc-scrape-examples = true

[[example]]
name = "rustls_session"
required-features = ["tls-rustls"]
doc-scrape-examples = true
