[package]
authors = ["0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "High level server for hyper and tower."
edition = "2021"
homepage = "https://github.com/valorem-labs-inc/hyper-server"
keywords = ["tokio", "tonic", "hyper", "tower", "server"]
license = "MIT"
name = "hyper-server"
readme = "README.md"
repository = "https://github.com/valorem-labs-inc/hyper-server"
version = "1.0.0"

[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.4.1", features = ["server"] }
hyper-util = { version = "0.1.7", features = ["service", "tokio", "http1"] }
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread", "macros"] }
tower = { version = "0.5.0", features = ["util"] }
tracing = "0.1.40"
