[package]
authors = ["0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
description = "High level server for hyper and tower."
edition = "2021"
homepage = "https://github.com/warlock-labls/hyper-server"
keywords = ["axum", "tonic", "hyper", "tower", "server"]
license = "MIT"
name = "hyper-server"
readme = "README.md"
repository = "https://github.com/valorem-labs-inc/hyper-server"
version = "1.0.0"

[dependencies]